version: "3.9"

services:

  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"

  servers:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - nats
